### ISSUE TITLE
spox.Var cannot be copied

### ISSUE THREAD

**Issue by cbourjau** [Quantco/spox#139]
Making a shallow copy of a `spox.Var` object leads to an error at build time. While it seems reasonable that a `copy.deepcopy` would not work, it seems surprising from a user perspective that a shallow copy is also causing issues. 

**[Failing test case](https://github.com/Quantco/spox/commit/db65f8dc876757720de151a054e04f271d17b9bb):**

```python
def test_copy_vars():
    from copy import copy

    a = argument(Tensor(float, ()))
    b = op.add(a, copy(a))
    build({"a": a}, {"b": b})
```

**Stack trace:**
```
    def test_copy_vars():
        from copy import copy
        a = argument(Tensor(float, ()))
        b = op.add(a, copy(a))
>       build({"a": a}, {"b": b})

tests/test_public.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/spox/_public.py:117: in build
    return graph.to_onnx_model()
src/spox/_graph.py:390: in to_onnx_model
    opsets = self.get_opsets()
src/spox/_graph.py:249: in get_opsets
    return max_opset_policy(self._get_opset_req())
src/spox/_graph.py:259: in _get_opset_req
    return self._get_build_result().opset_req | (
src/spox/_graph.py:254: in _get_build_result
    self._build_result.value = _build.Builder(self).build_main()
src/spox/_build.py:203: in build_main
    return self.compile_graph(self.main, Scope())
src/spox/_build.py:456: in compile_graph
    nodes[node] = tuple(node.to_onnx(scope, build_subgraph=build_subgraph))
src/spox/_node.py:354: in to_onnx
    input_names = [scope.var[var] if var is not None else "" for var in self.inputs]
src/spox/_node.py:354: in <listcomp>
    input_names = [scope.var[var] if var is not None else "" for var in self.inputs]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <spox._scope.ScopeSpace object at 0x10febc390>
item = <Var from spox.internal@0::Argument->?? of float64>

    def __getitem__(self, item: Union[str, H]):
        """Access the name of an object or an object with a given name in this (or outer) namespace."""
        if self.parent is not None and item in self.parent:
            return self.parent[item]
        elif isinstance(item, str):
            return self.of_name[item]
        else:
>           return self.name_of[item]
E           KeyError: <Var from spox.internal@0::Argument->?? of float64>

src/spox/_scope.py:76: KeyError
```

In any case, we should consider adding a [`__deepcopy__`](https://docs.python.org/3/library/copy.html#copy.deepcopy) method to `Var` which raises a more helpful exception immediately.

**Comment by adityagoel4512** [comment]
I suppose even a shallow copy does not buy you much given Vars themselves are immutable. Agree the error message could be improved, though.

**Comment by cbourjau** [comment]
Yes, there is not reason to copy a `Var`, but it should not result in a cryptic error.

**Comment by jbachurski** [comment]
In principle even a shallow copy of a non-argument is not.. useless, just difficult to say what a use case could be. Deep copies would always break the entire dependency graph. Either way, the reason an error is raised here is because the shallow copy changes the object identity of the argument (a), and b ends up depending on an argument (copy(a)) which is not declared in build.

Perhaps the best way is to add an explicit error check for missing arguments in build. But it’s probably fine to implement a deep copy too (there’s no mutable state anyway, well, except for hacks like cast).

**Comment by jbachurski** [comment]
> Technically, two `Var`s should be equal and have the same hash if they were produced by the same node and are connected to the same "output index" of that node. Do you see a reason why that should not form the basis of the hash which would naturally make things work with a shallow copy?

I'm not completely sure what you mean by 'naturally'. I see the following options:

* Don't do anything when shallow copying, just return the existing instance.
* Actually perform a shallow copy by reconstructing the Var. This would change the identity and hence equality test.
* Allow shallow copies and use a shallow hash by of the node identity and pointed output.

I would definitely not do anything in way of deep copies nor deep hashes, as those would require a lot of complexity for virtually no gain. Spox would essentially end up implementing common subexpression elimination (so that deep-copied Vars still compare equal), and that should be done by optimisers.

Unless there's a specific problem, I'm not sure there's anything worth doing here except returning the same object? If you think that's bad style that the copy has the same identity, then you can do your shallow hash idea.

**Comment by cbourjau** [comment]
Returning the identical object from a copy seems a bit iffy, but I can't point to a place where that would cause an issue, to be honest. It would certainly be the easiest way to address this issue!
