### ISSUE TITLE
How to choose between this project and onnxscript?

### ISSUE THREAD

**Issue by vincentme** [Quantco/spox#151]
Hi

My goal is to write algorithms in ONNX format, not necessarily deep learning models. I am a novice to both libraries, but it seems that they can all fulfill this task. Could you give me some hints and suggestions?

**Comment by jbachurski** [comment]
This is from the technical side of things, but I've been less involved for the last year of so. Unless much has changed, Spox is much more flexible than ONNX Script, as it uses a proper functional-style DSL embedding. This means you can have Python containers (lists, dictionaries, etc) of Spox ONNX-values (Vars), and write "macros" with just simple Python functions. Do consider looking at docs for examples. In contrast, ONNX Script focus on parsing ASTs of functions written in a strict subset of Python.

QuantCo use it in practice for building converter libraries for sklearn-style model components. Any extra thoughts @cbourjau ?

For non deep-learning stuff I would definitely use Spox personally. ONNX Script obviously has tons of work towards making it work with Torch and such.

**Comment by vincentme** [comment]
Thank you for the explanation!

**Comment by cbourjau** [comment]
Thanks @jbachurski for the summary! I think it is fair to say that Spox is more "Pythonic" than ONNXscript. In Spox, you write regular Python code that operates on regular Python objects. We developed Spox because non of the tools in the field met our requirements of developer productivity and maintainability. We are using Spox every day here at QuantCo to convert large sklearn-like pipelines (including feature engineering) into ONNX models with ~10k nodes. Unfortunately, that converter code is not open source, though. 

Since you explicitly ask about algorithms: It is certainly possible to express complex logic in ONNX via Spox. In fact, there is a BF-interpreter written in ONNX (via Spox) in the test suite: https://github.com/Quantco/spox/blob/main/tests/full/test_turing_completeness.py

**Comment by vincentme** [comment]
Good to know that, thanks!
