### ISSUE TITLE
A comparison documentation to onnxscript

### ISSUE THREAD

**Issue by ogencoglu** [Quantco/spox#168]
Would it be possible to have a short page comparing spox and [onnxscript](https://github.com/microsoft/onnxscript)? Maybe a table of main feature differences or couple of short paragraphs explaining the differences.

**Comment by cbourjau** [comment]
I am not much of an onnxscript user but here is my take. Is that what you'd be looking for?

onnxscript has a slightly different scope than Spox. Spox exposes the ONNX standard through a regular Python API. Graphs are defined by executing regular Python code that creates `spox.Var` objects. Spox has a strong focus on providing a great developer experience by raising errors as soon as they are discoverable. In particular, this means that Spox strives to offer comprehensive type and shape inference at every individual step and allows for setting debugger break points or using print statements at any point - it is regular Python code after all.

onnxscript, on the other hand (as I understand it), doesn't execute functions with the Python interpreter in order to build an ONNX graph. Instead, it relies on parsing the abstract syntax tree (AST). This is to some extend akin to writing an ONNX-backed Python interpreter in Python. The result is that only a subset of the Python language may be used and I imagine that setting breakpoints, print statements, and any other side effects that are allowed in Python may produce rather surprising effects.

The onnxscript project furthermore encopases other subprojects that go beyond the scope of Spox. For instance, it also defines an "optimizer" and a "rewriter". These may be applied to graphs produced by Spox, but they may be less relevant for Spox users. For instance, `spox.build` already eliminates dead code (except within inlined models). Furthermore, a [considerable part](https://onnxscript.ai/tutorial/optimizer/optimize.html#description-of-optimizations-applied-by-onnxscript-optimizer-optimize) of the optimizations is concerned with "ONNX functions" which Spox doesn't use.

The rewriter may be less useful for Spox users since such rules can often be directly expressed in Python functions when building a graph in the first place. 

Another library to compare with is [skl2onnx](https://github.com/onnx/sklearn-onnx) which we used a lot to get started on our QuantCo ONNX journey. The main difference to that library is that the Spox user never has to worry about node and edge nameing, nor about the global state of the graph that is being build (i.e. the "scope" and "container" objects in skl2onnx).

**Comment by ogencoglu** [comment]
Thanks for the clarification!

I am familiar with `skl2onnx` and what I am after is a library to fill the gaps. For example onnx has all sorts of support issues with scikit learn models that has categorical features (any tree-based stuff). skl2onnx conversion would treat it as float. I need a tool to load that converted onnx model, easily modify that logic and add some if-else there, save it again in onnx. These sort of use cases.
