### ISSUE TITLE
Adding a conditional (if-else logic) and combining several ONNX models into one

### ISSUE THREAD

**Issue by ogencoglu** [Quantco/spox#169]
I have several ONNX models that have been converted from `scikit-learn` with `skl2onnx`. They take the same numerical features as input. I would like to add a simple if-else logic (let's say based on one of the numerical input variables) to decide which onnx model to route to. 

Can I achieve this in spox? Specifically:
- read N onnx models
- write a custom conditional logic at the top
- attach each model's onnx graph to the if-else logic
- save the result as a single ONNX file

The goal is to merge different ONNX files into one with a conditional logic.

**Comment by cbourjau** [comment]
Yes, that is well covered and we are doing something similar in production since a while. The relevant parts in the docs are:
- Inlining existing ONNX models: https://spox.readthedocs.io/en/latest/guides/inline.html
- Control flow with the `If` operator: https://spox.readthedocs.io/en/latest/guides/advanced.html#Control-flow

There is nothing special about "attaching" a model to the if-else logic; things should just work. The same is true for saving the resulting model into a single file. If you haven't already, I also recommend you to take a look at the [tutorial](https://spox.readthedocs.io/en/latest/guides/tutorial.html) in the docs which should cover all the basics that you need and a little more.

Please let us know how it worked out for you!

**Comment by ogencoglu** [comment]
Thanks, I will try that out.
